In [2]:
import torch
torch.__version__

'2.1.2+cu118'

In [3]:
torch.cuda.is_available()

True

In [6]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [5]:
torch.cuda.device_count()

1

In [7]:
tensor = torch.tensor([1,2,3,])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [11]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3], dtype=int64)